# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "events", :force => true do |t|
    t.column "name", :string
  end

  create_table "friends", :force => true do |t|
    t.column "name", :string
    t.column "email", :string
  end

  create_table "schedules", :force => true do |t|
    t.column "range", :string
    t.column "sunday", :string
    t.column "monday", :string
    t.column "tuesday", :string
    t.column "wednesday", :string
    t.column "thursday", :string
    t.column "friday", :string
    t.column "saturday", :string
  end

  create_table "specials", :force => true do |t|
    t.column "day", :string
    t.column "lunch", :string
    t.column "dinner", :string
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "remember_token", :string
    t.column "remember_token_expires_at", :datetime
  end

end
